### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by renanivo** [drgarcia1986/drf-pdf#14]
It would be nice to have a documentation with:

1. Basic Usage
2. API Guide

The basic usage is available in the `README`, but I'm afraid documenting features there, like #13 and #12, could compromise brevity. It could produce a little duplication in the docs but [DRF](django-rest-framework.org) itself does it (Take a look at [their README](https://github.com/tomchristie/django-rest-framework#readme) and [docs index](http://www.django-rest-framework.org/)).

If you agree with the API Guide, we need to know which tool to use. There are some options like [Sphinx](http://sphinx-doc.org/) and [MkDocs](http://www.mkdocs.org/) -- Sphinx can generate pages from docstrings but MkDocs has built-in MarkDown support.

**Comment by drgarcia1986** [comment]
I agree.
I like MkDocs approach, what you think @jairhenrique ?

**Comment by jairhenrique** [comment]
:+1: 

I vote to the most easy tool to write and deploy automatically, [RTD](https://readthedocs.org/) supports `MkDocs` and `Sphinx`. 
The [README](https://github.com/tomchristie/django-rest-framework#readme) is already written in `MarkDown`, so I think this approach could be continued.

**Comment by diegogarcia-luizalabs** [comment]
![tacalepal](http://imguol.com/c/noticias/2014/06/27/marcos-martinelli-12-ficou-famoso-na-web-com-video-taca-le-pau-sic-1403899099030_956x500.jpg)

**Comment by drgarcia1986** [comment]
![tacalepal](http://imguol.com/c/noticias/2014/06/27/marcos-martinelli-12-ficou-famoso-na-web-com-video-taca-le-pau-sic-1403899099030_956x500.jpg)

**Comment by renanivo** [comment]
Agreed. Actually I already started creating a documentation with MkDocs.

I just have one question: What about writing docstrings, even if they didn't end up being used to generate docs, do you think it's worth to write it for the public API (Renderers and Responses)?

**Comment by jairhenrique** [comment]
@renanivo docstrings are useful for tools like [IDE](http://en.wikipedia.org/wiki/Integrated_development_environment) and [IPython](http://ipython.org/). I like this, but `MkDocs` and `docstrings` must walk together.
